name: Build RTL8720dn-Deauther

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | bash
        echo "$HOME/bin" >> $GITHUB_PATH
        arduino-cli version

    - name: Add board manager URL for Ameba platform
      run: |
        arduino-cli config init
        arduino-cli config set board_manager.additional_urls https://github.com/ambiot/ambd_arduino/raw/master/Arduino_package/package_realtek.com_amebad_index.json
        arduino-cli config dump

    - name: Install AmebaD board support
      run: |
        arduino-cli core update-index
        arduino-cli core install realtek:AmebaD

    - name: Compile firmware and export binaries
      run: |
        mkdir -p ./build
        arduino-cli compile --fqbn realtek:AmebaD:Ai-Thinker_BW16 --export-binaries --output-dir ./build .

    - name: Create a new tag
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag v1-d
        git push origin v1-d

    - name: Upload compiled firmware to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
